name: iOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.DEVOXX_IOS_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.DEVOXX_IOS_CERTIFICATES_PASSWORD }}

      - uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.devoxx.badges.devoxxbadges
          issuer-id: ${{ secrets.DEVOXX_IOS_APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.DEVOXX_IOS_APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.DEVOXX_IOS_APPSTORE_PRIVATE_KEY }}

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v2
        with:
          dir: .
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Bundle version
        id: variables
        run: |
          echo "::set-output name=VERSION::$((100 + GITHUB_RUN_NUMBER))"
        shell: bash

      - name: Gluon Build
        run: |
          mvn -Pios -DiosSignIdentity="${{ secrets.DEVOXX_SIGN_IDENTITY }}" -DiosProvisioningProfile="${{ secrets.DEVOXX_PROV_PROFILE }}" -Dbundle.version="$BUNDLE_VERSION" gluonfx:build gluonfx:package
        env:
          BUNDLE_VERSION: ${{ steps.variables.outputs.VERSION }}
        
      - uses: Apple-Actions/upload-testflight-build@master
        with:
          app-path: target/gluonfx/arm64-ios/DevoxxBadges.ipa
          issuer-id: ${{ secrets.DEVOXX_IOS_APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.DEVOXX_IOS_APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.DEVOXX_IOS_APPSTORE_PRIVATE_KEY }}
